package com.tw;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    private Scanner sc;
    private LibraryService service;

    public boolean someLibraryMethod() {
        return true;
    }

    public Library() {
        sc = new Scanner(System.in);
        service = new LibraryService();
        mainView();
    }

    private void mainView() {
        System.out.println("1. 添加学生\n2. 生成成绩单\n3. 退出\n请输入你的选择（1～3）：");
        String pick = sc.nextLine();
        switch (pick) {
            case "1": addStudent(true);
            case "2": generateReports(true);
            case "3": exit();
            default: mainView();
        }
    }

    private void addStudent(boolean firstAttempt) {
        System.out.println(firstAttempt ? "请输入学生信息（格式：姓名, 学号, 学科: 成绩, ...），按回车提交：" :
                "请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：");

        boolean success = service.addStudent(sc.nextLine());
        if (success) {
            mainView();
        } else {
            addStudent(false);
        }

    }

    private void generateReports(boolean firstAttempt) {
        System.out.println(firstAttempt ? "请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：" :
                "请按正确的格式输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：");

        boolean success = service.generateReports(sc.nextLine());
        if (success) {
            mainView();
        } else {
            generateReports(false);
        }

    }

    private void exit() {
        sc.close();
        System.exit(-1);
    }
}
